fields:
  tokopedia:
    group: 'marketplace'
    tribe: 'content'
    service: 'feeds'
    direct_dependencies: []

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'

setup:
  kibana:
    host: '${KIBANA_HOSTS:kibana:5601}'
  