metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

metricbeat.modules:
# - module: ecs
#   enabled: true
#   period: 10s
- module: system
  enabled: false
  period: 10s
  processes: ['.*']

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'

setup:
  kibana:
    host: '${KIBANA_HOSTS:kibana:5601}'
  template:
    name: 'custom_template'
    fields: '/etc/metricbeat/fields.yml'